site_name: ç¥ç§˜ç¤¼ç‰© Â· Emby Wiki
site_description: ç§æœ‰ Emby ä½¿ç”¨è¯´æ˜ä¸è§„åˆ™æ–‡æ¡£
site_author: ç¥ç§˜ç¤¼ç‰©

theme:
  name: material
  language: zh

  icon:
    logo: material/gift

  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢åˆ°æ·±è‰²æ¨¡å¼

    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢åˆ°æµ…è‰²æ¨¡å¼

  features:
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/smlw22

nav:
  - ğŸ  é¦–é¡µ:
      - index.md

  -  å¦‚ä½•åŠ å…¥:
      - ğŸ’³ å…¬è´¹æœè¯´æ˜: guide/paid.md
      - ğŸŒ± å…¬ç›Šæœè¯´æ˜: guide/public.md

  - æ’­æ”¾è¯´æ˜:
      - ğŸ¬ å®¢æˆ·ç«¯ä¸æ’­æ”¾è¯´æ˜: client/player.md

  -  FAQ:
      - â“å¸¸è§é—®é¢˜: faq.md

  -  å…¶ä»–:
      - âš ï¸ ä½¿ç”¨å£°æ˜: statement.md
      - ğŸ“¢ å®˜æ–¹è”ç³»: contact.md